unsigned long int extract_list_of_business_filenames_to_parseable_ram_step_one_determine_total_delmiters(FILE * list_of_businesses_dot_text);
//int extract_list_of_business_filenames_to_parseable_ram(char ** list_of_business_records, char ** list_of_business_records_string_buffer_length, unsigned long int * list_of_business_records_total);
